
import java.sql.Connection;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.scene.input.KeyCode.F10;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ttran
 */
public class CustomerInvoice extends java.awt.Frame {

    public static int customerID;
    static final String tableName="orderdetails";
    final String customerTable="customer";
    ShuttersFrame shutterFrm = null;
    private String WindowStyle = "";
    public static final int WINDOW_STYLE_STANDARD = 1;
    public static final int WINDOW_STYLE_FRAME2FRAME = 2;
    
    private String custName;
    
    /**
     * Creates new form CustomerInvoice
     */
    public CustomerInvoice() {
        try {        
            initComponents();
            
            startUp();
        } catch (Exception ex) {
            Logger.getLogger(CustomerInvoice.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setWindowStyle(String style){
        WindowStyle = style;
    }
    
    public String getWindowStyle(){
        return WindowStyle;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGrpWindowStyle = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jInvoiceFld = new javax.swing.JTextField();
        jNameFld = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jFindBtn = new javax.swing.JButton();
        jAddBtn = new javax.swing.JButton();
        jOrderBtn = new javax.swing.JButton();
        jExitBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jRadioWindowStd = new javax.swing.JRadioButton();
        jRadioWindowFtoF = new javax.swing.JRadioButton();

        setTitle("Pacific Wholesale Shutters and Blinds");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Invoice Number:");

        jInvoiceFld.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jInvoiceFld.setNextFocusableComponent(jNameFld);

        jNameFld.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Customer Name:");

        jFindBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jFindBtn.setMnemonic('F');
        jFindBtn.setText("Find");
        jFindBtn.setNextFocusableComponent(jAddBtn);
        jFindBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFindBtnActionPerformed(evt);
            }
        });

        jAddBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jAddBtn.setMnemonic('A');
        jAddBtn.setText("Add");
        jAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddBtnActionPerformed(evt);
            }
        });

        jOrderBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jOrderBtn.setMnemonic('O');
        jOrderBtn.setText("Order Details");
        jOrderBtn.setEnabled(false);
        jOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOrderBtnActionPerformed(evt);
            }
        });

        jExitBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jExitBtn.setMnemonic('E');
        jExitBtn.setText("Exit");
        jExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitBtnActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Window Style", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        buttonGrpWindowStyle.add(jRadioWindowStd);
        jRadioWindowStd.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioWindowStd.setSelected(true);
        jRadioWindowStd.setText("Standard");
        jRadioWindowStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioWindowStdActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioWindowStd);

        buttonGrpWindowStyle.add(jRadioWindowFtoF);
        jRadioWindowFtoF.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioWindowFtoF.setText("Frame to Frame");
        jRadioWindowFtoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioWindowFtoFActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioWindowFtoF);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jInvoiceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jFindBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(194, 194, 194)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jNameFld)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInvoiceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jFindBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void startUp() throws Exception{
        jInvoiceFld.requestFocus();
        shutterFrm = new ShuttersFrame();
        shutterFrm.setParentFrame(this);
    }
    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jExitBtnActionPerformed

    private void jOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOrderBtnActionPerformed
        try {
//            if (shutterFrm == null)
//             shutterFrm= new ShuttersFrame();
            launchOrderDetails();
            int custID = Integer.valueOf(jInvoiceFld.getText());
            String custName = jNameFld.getText();
            shutterFrm.setCustID(custID);
            shutterFrm.setCustName(custName);
            shutterFrm.populateOrderByID(String.valueOf(custID));
            shutterFrm.resetFields();
            shutterFrm.setSquareFootage();

            
            if (jRadioWindowStd.isSelected()){
                shutterFrm.setWindowStyle(WINDOW_STYLE_STANDARD);
                shutterFrm.disableFinishedFields();
                shutterFrm.enableStandardFields();
            }
            else if (jRadioWindowFtoF.isSelected()){
                shutterFrm.setWindowStyle(WINDOW_STYLE_FRAME2FRAME);
                shutterFrm.enableFinishedFields();
                shutterFrm.disableStandardFields();
            }
            
        } catch (Exception ex) {
            Logger.getLogger(CustomerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }    }//GEN-LAST:event_jOrderBtnActionPerformed

    private void jFindBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFindBtnActionPerformed
        String name = findCustomerByID();
        if (name.length() > 0){
            jNameFld.setText(name);
            custName = name;
            jOrderBtn.setEnabled(true);
        }    }//GEN-LAST:event_jFindBtnActionPerformed

    private void jAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddBtnActionPerformed
        int custID = Integer.parseInt(jInvoiceFld.getText());
        String custName = jNameFld.getText();
        boolean bResult = addCustomer(custID, custName);
        if (bResult){
            jOrderBtn.setEnabled(bResult);
        }
    }//GEN-LAST:event_jAddBtnActionPerformed

    private void jRadioWindowStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioWindowStdActionPerformed
        if (jRadioWindowStd.isSelected())
            shutterFrm.setWindowStyle(WINDOW_STYLE_STANDARD);
    }//GEN-LAST:event_jRadioWindowStdActionPerformed

    private void jRadioWindowFtoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioWindowFtoFActionPerformed
        if (jRadioWindowFtoF.isSelected())
            shutterFrm.setWindowStyle(WINDOW_STYLE_FRAME2FRAME);
    }//GEN-LAST:event_jRadioWindowFtoFActionPerformed

    public String getCustName(){
        return custName;
    }
    
    public boolean addCustomer(int custID, String custName){
        boolean bResult = true;
        Connection conn = null;
        MySqlConnection mySqlConn = new MySqlConnection();
        try {
            mySqlConn.getUser();
            conn = mySqlConn.getConnection();
            if (conn != null){
                Statement stmt = conn.createStatement();
                String sql = "INSERT INTO " + customerTable + " values("
                            + custID + ","
                            + "'" + custName + "'" + ")";
                stmt.execute(sql);
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return bResult;
    }
    public String findCustomerByID(){
        String custName = "";
        String custID = jInvoiceFld.getText();
        try {
            
            if (shutterFrm == null)
                shutterFrm = new ShuttersFrame();
            custName = shutterFrm.getCustNameByID(custID);
        } catch (Exception ex) {
            Logger.getLogger(CustomerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return custName;
    }
    
    public void launchOrderDetails(){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    if (shutterFrm != null)
                    {
                        shutterFrm.setVisible(true);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(ShuttersFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }    
        });
    }
    
    public int getCustomerID(){
        int custID = this.customerID;
        return custID;
    }
    
    public void setCustomerID(int custID){
        this.customerID = custID;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerInvoice().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGrpWindowStyle;
    private javax.swing.JButton jAddBtn;
    private javax.swing.JButton jExitBtn;
    private javax.swing.JButton jFindBtn;
    private javax.swing.JTextField jInvoiceFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jNameFld;
    private javax.swing.JButton jOrderBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioWindowFtoF;
    private javax.swing.JRadioButton jRadioWindowStd;
    // End of variables declaration//GEN-END:variables
}
